---
title: "Quizz - Practice Functions, Loops etc."
author: "Billy"
date: "2023-11-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Practice Functions

The first section of code provides you with the different functions used for the practice quiz. After finishing the quiz feel free to alter them yourself to explore use-cases.

```{r "function creation"}
# Practice function 1
function_1 <- function () {
  return(10 * 3)
}

# Practice function 2
function_2 <- function (x, y) {
  return(x * y)
}

# Practice function 3
function_3 <- function (x = 10, y = 3) {
  return(x * y)
}

# Practice function 4
function_4 <- function (x, y = 10) {
  inner_function <- function (z) {
    return(x * y * z)
  }
  return(inner_function)
}

# Practice function 5
function_5 <- function (x = 10, y = 3, ...) {
  z <- x + y
  if (length(list(...)) > 0) {
    z <- z + sum(...)
  }
  return(z)
}

# Practice function 6
function_6 <- function (x = 10) {
  if (x == 0 | x == 1) {
    return(1)
  } else {
    return(x * function_6(x - 1))
  }
}

function_1(20)
function_2(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
function_3(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
res <- function_4(4,10)
class(res)
res(1:3)
function_5(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
function_6(10)

```

Below you find the function call. Use different function names (e.g., function_1, function_9) and arguments to answer the quiz questions.

```{r "function call"}
# Try out different function calls below...
function_2()
```

## 
